title: 	サンプル論文サンプル論文サンプル論文サンプル論文
category: domestic-paper
book: ほげほげ研究報告
author_ja:
  - ほげ 太郎
  - ふが 次郎
  - ぴよ 三郎
author_en: 
  - Taro Hoge
  - Jiro Fuga
  - Saburo Piyo
volume: 134
number: 2332
pages: 98-100
year: 2023
month: 6
url: 	https://example.com/
abstract: 要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約要約
